# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [45]:
import torch

Construct a 5x3 matrix, uninitialized

In [46]:
x = torch.Tensor(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [   nan, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


Construct a randomly initialized matrix

In [47]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1012, 0.5491, 0.6420],
        [0.2678, 0.7351, 0.3605],
        [0.8661, 0.9348, 0.8861],
        [0.5668, 0.2986, 0.6602],
        [0.9540, 0.5069, 0.3532]])


Get its size

In [48]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [49]:
x[1:3] = 2
print(x)

tensor([[0.1012, 0.5491, 0.6420],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.5668, 0.2986, 0.6602],
        [0.9540, 0.5069, 0.3532]])


# Assignment

1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [50]:
# Make a tensor of size (2, 17)

ten = torch.Tensor(2, 17)
print(x.size())

torch.Size([5, 3])


In [51]:
# Make a torch.FloatTensor of size (3, 1)

f = torch.FloatTensor(3,1)
print(f.type(), f.size())

torch.FloatTensor torch.Size([3, 1])


In [52]:
# Make a torch.LongTensor of size (5, 2, 1)

lt = torch.LongTensor(5, 2, 1)
print(lt.type(), lt.size())

# fill it with 7s
lt[:] = 7
print(lt)

torch.LongTensor torch.Size([5, 2, 1])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])


In [53]:
bt = torch.ByteTensor(5,)
print(bt)
bt[1:4] = 1
print(bt)

tensor([0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [54]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.8117, 1.0315, 1.1967],
        [2.4247, 2.6948, 2.2417],
        [2.8717, 2.9669, 2.4825],
        [0.8315, 0.8140, 1.6363],
        [1.4664, 1.3792, 0.6584]])


### 2.2 Addition: syntax 2

In [55]:
print(torch.add(x, y))

tensor([[0.8117, 1.0315, 1.1967],
        [2.4247, 2.6948, 2.2417],
        [2.8717, 2.9669, 2.4825],
        [0.8315, 0.8140, 1.6363],
        [1.4664, 1.3792, 0.6584]])


### 2.3 Addition: giving an output tensor

In [56]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8117, 1.0315, 1.1967],
        [2.4247, 2.6948, 2.2417],
        [2.8717, 2.9669, 2.4825],
        [0.8315, 0.8140, 1.6363],
        [1.4664, 1.3792, 0.6584]])


### 2.4 Addition: in-place

adds `x`to `y`

In [57]:
y.add_(x)
print(y)

tensor([[0.8117, 1.0315, 1.1967],
        [2.4247, 2.6948, 2.2417],
        [2.8717, 2.9669, 2.4825],
        [0.8315, 0.8140, 1.6363],
        [1.4664, 1.3792, 0.6584]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [58]:
print(x[:, 1])

tensor([0.5491, 2.0000, 2.0000, 0.2986, 0.5069])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [59]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [60]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [61]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [62]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [68]:
on = torch.ones(5,2)
print(on)
onp = a.numpy()
print(onp)
btt = torch.from_numpy(onp)
print(btt)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [64]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:# Make a torch.LongTensor of size (5, 2, 1)

lt = torch.LongTensor(5, 2, 1)
print(lt.type(), lt.size())# Make a torch.LongTensor of size (5, 2, 1)

lt = torch.LongTensor(5, 2, 1)
print(lt.type(), lt.size())
    print("CUDA not available on your machine.")

IndentationError: expected an indented block (<ipython-input-64-cf6b7428044a>, line 14)